-- PostgreSQL DDL converted from the supplied draw.io ERD (16 tables).
-- Revised MVP schema. Run once in an empty database/schema. No existing data is dropped.
-- This is a full schema, not an ALTER migration for an already-created database.
-- Assumptions: BIGINT identity IDs; NUMERIC(18,2) money; TIMESTAMPTZ timestamps.
-- Names normalized to snake_case/plural to avoid reserved User and Order names.
-- Corrections: Staff.staff _id -> staff_id; Staff.brand_id -> branch_id;
-- duplicate EventImage.image_url collapsed into one column.
-- Foreign keys follow the explicitly marked FK columns, not ambiguous connectors.
-- Status CHECK values are proposed MVP business rules; coordinate with backend enums.
-- NOT NULL, lengths, defaults, uniqueness and CHECK constraints below are inferred.
-- EventDetail.event_id is UNIQUE to enforce the drawn one-to-one relationship.
-- duration is assumed to be minutes; rental dates are calendar dates.
-- Transactions reference exactly one order OR participant (event_id replaced).
-- Resolve event via participant -> schedule -> event. Amounts are positive; type gives direction.
-- One inventory row per branch/product; one participant row per schedule/user.
-- Re-registration updates the same participant row; retain prior transactions.
-- registered_price snapshots the per-person price when registering.
-- Rentals track quantities rather than individually serialized equipment.
-- Each event schedule belongs to its organizing branch.
-- Product sale and rental prices are separate; NULL means that mode is unavailable.
-- At least one price is required. Rental unit_price snapshots the daily rate;
-- SALE line total = quantity * unit_price; RENTAL also multiplies by billed days.
-- Application must define billed days consistently (e.g. inclusive calendar dates).
-- Password must contain a password hash generated by the application.

BEGIN;

CREATE TABLE roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(role_id),
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(30),
    password VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE branches (
    branch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR(150) NOT NULL,
    phone VARCHAR(30),
    address TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE staff (
    staff_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id),
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    position VARCHAR(100),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    category VARCHAR(100),
    sale_price NUMERIC(18,2) CHECK (sale_price >= 0),
    rental_price_per_day NUMERIC(18,2) CHECK (rental_price_per_day >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_products_price_mode CHECK (
        sale_price IS NOT NULL OR rental_price_per_day IS NOT NULL
    )
);

CREATE TABLE inventory (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id),
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    quantity_total INTEGER NOT NULL DEFAULT 0 CHECK (quantity_total >= 0),
    quantity_available INTEGER NOT NULL DEFAULT 0 CHECK (quantity_available >= 0),
    quantity_rented INTEGER NOT NULL DEFAULT 0 CHECK (quantity_rented >= 0),
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT uq_inventory_branch_product UNIQUE (branch_id, product_id),
    CONSTRAINT ck_inventory_quantities CHECK (
        quantity_available::BIGINT + quantity_rented::BIGINT <= quantity_total::BIGINT
    )
    -- Remaining stock may be damaged/reserved; equality is not required.
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id),
    order_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    order_status VARCHAR(30) NOT NULL DEFAULT 'PENDING'
        CHECK (order_status IN ('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    total_amount NUMERIC(18,2) NOT NULL CHECK (total_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    item_type VARCHAR(30) NOT NULL CHECK (item_type IN ('SALE', 'RENTAL')),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(18,2) NOT NULL CHECK (unit_price >= 0),
    rental_start_date DATE,
    rental_end_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'CONFIRMED', 'FULFILLED', 'RENTED', 'RETURNED', 'CANCELLED')),
    CONSTRAINT ck_order_items_rental_dates CHECK (
        (item_type = 'SALE' AND rental_start_date IS NULL AND rental_end_date IS NULL)
        OR (item_type = 'RENTAL' AND rental_start_date IS NOT NULL
            AND rental_end_date IS NOT NULL AND rental_end_date >= rental_start_date)
    )
);

CREATE TABLE tour_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(200) NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    description TEXT,
    location TEXT,
    base_price NUMERIC(18,2) NOT NULL CHECK (base_price >= 0),
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    -- updated_at must be updated by the application on subsequent changes.
);

CREATE TABLE event_details (
    event_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL UNIQUE REFERENCES tour_events(event_id),
    duration INTEGER CHECK (duration > 0),
    difficulty_level VARCHAR(50),
    meeting_point TEXT,
    requirements TEXT
);

CREATE TABLE event_images (
    image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES tour_events(event_id),
    image_url TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tour_guides (
    guide_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    experience_years INTEGER CHECK (experience_years >= 0),
    specialization TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE event_schedules (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES tour_events(event_id),
    branch_id BIGINT NOT NULL REFERENCES branches(branch_id),
    guide_id BIGINT REFERENCES tour_guides(guide_id),
    start_datetime TIMESTAMPTZ NOT NULL,
    end_datetime TIMESTAMPTZ NOT NULL,
    max_participants INTEGER NOT NULL CHECK (max_participants > 0),
    current_participants INTEGER NOT NULL DEFAULT 0 CHECK (current_participants >= 0),
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'FULL', 'CLOSED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_event_schedules_time CHECK (end_datetime > start_datetime),
    CONSTRAINT ck_event_schedules_capacity CHECK (current_participants <= max_participants)
);

CREATE TABLE event_schedule_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL REFERENCES event_schedules(schedule_id),
    old_start_datetime TIMESTAMPTZ,
    new_start_datetime TIMESTAMPTZ,
    old_end_datetime TIMESTAMPTZ,
    new_end_datetime TIMESTAMPTZ,
    old_status VARCHAR(30),
    new_status VARCHAR(30),
    change_reason TEXT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE event_participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id BIGINT NOT NULL REFERENCES event_schedules(schedule_id),
    user_id BIGINT NOT NULL REFERENCES users(user_id),
    registration_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    participant_status VARCHAR(30) NOT NULL DEFAULT 'PENDING'
        CHECK (participant_status IN ('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    check_in_status VARCHAR(30) NOT NULL DEFAULT 'NOT_CHECKED_IN'
        CHECK (check_in_status IN ('NOT_CHECKED_IN', 'CHECKED_IN')),
    registered_price NUMERIC(18,2) NOT NULL CHECK (registered_price >= 0),
    note TEXT,
    CONSTRAINT uq_event_participants_schedule_user UNIQUE (schedule_id, user_id)
    -- Re-registration updates this row rather than creating a duplicate.
    -- current_participants must be maintained transactionally by the application.
);

CREATE TABLE transactions (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(order_id),
    participant_id BIGINT REFERENCES event_participants(participant_id),
    transaction_type VARCHAR(30) NOT NULL CHECK (transaction_type IN ('PAYMENT', 'REFUND')),
    amount NUMERIC(18,2) NOT NULL CHECK (amount > 0),
    payment_method VARCHAR(50) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_transactions_target CHECK (
        (order_id IS NOT NULL AND participant_id IS NULL)
        OR (order_id IS NULL AND participant_id IS NOT NULL)
    )
    -- Multiple payments/refunds per target are allowed; enforce refundable balance in service.
);

-- Composite UNIQUE indexes also cover their leftmost FK column.
-- Index the remaining foreign keys.
CREATE INDEX idx_users_role_id ON users(role_id);
CREATE INDEX idx_staff_branch_id ON staff(branch_id);
CREATE INDEX idx_staff_user_id ON staff(user_id);
CREATE INDEX idx_inventory_product_id ON inventory(product_id);
CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_branch_id ON orders(branch_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_product_id ON order_items(product_id);
CREATE INDEX idx_event_images_event_id ON event_images(event_id);
CREATE INDEX idx_tour_guides_user_id ON tour_guides(user_id);
CREATE INDEX idx_event_schedules_event_id ON event_schedules(event_id);
CREATE INDEX idx_event_schedules_branch_id ON event_schedules(branch_id);
CREATE INDEX idx_event_schedules_guide_id ON event_schedules(guide_id);
CREATE INDEX idx_event_schedule_history_schedule_id ON event_schedule_history(schedule_id);
CREATE INDEX idx_event_participants_user_id ON event_participants(user_id);
CREATE INDEX idx_transactions_order_id ON transactions(order_id);
CREATE INDEX idx_transactions_participant_id ON transactions(participant_id);

COMMIT;
