-- Module 4 only. Account/users must be provisioned by its owning module first.
-- IF NOT EXISTS also supports the shared ERD schema; no shared tables are created here.
CREATE TABLE IF NOT EXISTS tour_events (
 event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_name VARCHAR(200) NOT NULL, event_type VARCHAR(50) NOT NULL,
 description TEXT, location TEXT, base_price NUMERIC(18,2) NOT NULL CHECK (base_price >= 0),
 status VARCHAR(30) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS event_details (
 event_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id BIGINT NOT NULL UNIQUE REFERENCES tour_events(event_id),
 duration INTEGER CHECK (duration > 0), difficulty_level VARCHAR(50), meeting_point TEXT, requirements TEXT
);
CREATE TABLE IF NOT EXISTS event_images (
 image_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 event_id BIGINT NOT NULL REFERENCES tour_events(event_id), image_url TEXT NOT NULL,
 description TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE event_images ADD COLUMN IF NOT EXISTS cloudinary_public_id TEXT;
CREATE TABLE IF NOT EXISTS tour_guides (
 guide_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(user_id),
 experience_years INTEGER CHECK (experience_years >= 0), specialization TEXT,
 status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE'))
);
-- Existing incompatible data must be corrected explicitly; do not silently rewrite it.
ALTER TABLE tour_guides ALTER COLUMN specialization SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_guide_user_specialization
 ON tour_guides(user_id, LOWER(BTRIM(specialization)));
CREATE INDEX IF NOT EXISTS idx_event_images_event_id ON event_images(event_id);
CREATE INDEX IF NOT EXISTS idx_tour_guides_user_id ON tour_guides(user_id);
CREATE INDEX IF NOT EXISTS idx_tour_events_status_created ON tour_events(status, created_at DESC, event_id DESC);

ALTER TABLE tour_events ADD CONSTRAINT ck_tour_event_type CHECK (event_type IN ('TREKKING','CAMPING'));
ALTER TABLE event_details ADD CONSTRAINT ck_event_difficulty CHECK (difficulty_level IN ('EASY','MODERATE','HARD'));
ALTER TABLE tour_guides ADD CONSTRAINT ck_guide_specialization CHECK (LENGTH(BTRIM(specialization)) BETWEEN 1 AND 1000);
